
  services:
    mariadb:
      image: mariadb:11.3.2
      container_name: aqua_db
      restart: unless-stopped
      env_file:
        - .env
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - db_data:/var/lib/mysql
      ports:
        - "3306:3306"

    phpmyadmin:
      image: phpmyadmin:5.2.1-apache
      container_name: aqua_phpmyadmin
      restart: unless-stopped
      ports:
        - "8111:80"
      environment:
        PMA_HOST: mariadb
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      depends_on:
        - mariadb

  volumes:
    db_data:
